spring:
  application:
    name: elasticsearch-basic
  elasticsearch:
    rest:
      uris: http://localhost:9200
logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: TRACE
    com.junbetterway.spring.data.elasticsearch: DEBUG
